name:                kenken-game
version:             0.1.0.0
github:              "yourusername/kenken-game"
license:             BSD3
author:              "Your Name"
maintainer:          "your.email@example.com"
copyright:           "2024 Your Name"

extra-source-files:
- README.md

description:         KenKen puzzle game implementation in Haskell

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6.0.1
- array >= 0.5.4.0
- megaparsec >= 9.0.0
- text >= 1.2.4.1
- mtl >= 2.2.2
- directory >= 1.3.6.0
- filepath >= 1.4.2.1
- time >= 1.9.3
- ansi-terminal >= 0.11

library:
  source-dirs: src

executables:
  kenken-game-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kenken-game

tests:
  kenken-game-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kenken-game
    - hspec